---
# maps code to properties
"ABS_X":
  type: "ABS"
  name: "joystick_x_left"
  min : 0
  max : 65535 # right
"ABS_Y":
  type: "ABS"
  name: "joystick_y_left"
  min : 0
  max : 65535 # down
"ABS_RX":
  type: "ABS"
  name: "joystick_x_right"
  min : 0
  max : 65535 # right
"ABS_RY":
  type: "ABS"
  name: "joystick_y_right"
  min : 0
  max : 65535 # down
"ABS_HAT0X":
  type: "ABS"
  name: "dpad_x"
  min : -1
  max : 1 # right
"ABS_HAT0Y":
  type: "ABS"
  name: "dpad_y"
  min : -1
  max : 1 # down
"ABS_Z":
  type: "ABS"
  name: "trigger_left"
  min : 0
  max : 1023 # full down
"ABS_RZ":
  type: "ABS"
  name: "trigger_right"
  min : 0
  max : 1023 # full down
"BTN_A":
  type: "KEY"
  name: "a"
"BTN_B":
  type: "KEY"
  name: "b"
"BTN_C":
  type: "KEY"
  name: "x"
"BTN_NORTH":
  type: "KEY"
  name: "y"
"BTN_WEST":
  type: "KEY"
  name: "bumper_left"
"BTN_Z":
  type: "KEY"
  name: "bumper_right"
"BTN_TL2":
  type: "KEY"
  name: "thumb_left"
"BTN_TR2":
  type: "KEY"
  name: "thumb_right"
"BTN_TL":
  type: "KEY"
  name: "back"
"BTN_TR":
  type: "KEY"
  name: "start"
